<WeatherStation>:


    BoxLayout:
        orientation: 'vertical'
        size: 800,480
        size_hint: None, None

        Button:
            text: "Hello world, watch this text wrap inside the button"
            text_size: self.size
            font_size: '15sp'
            markup: True
        Button:
            text: "Hello world, watch this text wrap inside the button"
            text_size: self.size
            font_size: '15sp'
            markup: True
