openweather:
  url: https://api.openweathermap.org/data/3.0/onecall?lat={lat}&lon={lon}&units={units}&lang={lang}&appid={apikey}
  lat: 48.2083537
  lon: 16.3725042
  units: metric
  lang: de
  apikey: abdb6964a969eeceed4f072180f1d3a7

kivy:
  kv_directory: templates
  locale: de_DE.utf8
