openweather:
  url: https://api.openweathermap.org/data/3.0/onecall
  lat: 48.2083537
  lon: 16.3725042
  units: metric
  lang: de
  appid:   # your api key
  interval: 300  # Call every 5 Minutes (300 seconds), so we have 288 calls per day

mqtt:
  mqtt_host: 192.168.0.200

app:
  kv_directory: templates
  locale: de_DE.utf8
  height_above_sealevel: 210
  temperature_unit: °C
  pressure_unit: hPa
  humidity_unit: '%'
  battery_unit: V
  wifi_unit: dBm
  wind_unit: m/s
  clouds_unit: '%'
