openweather:
  url: https://api.openweathermap.org/data/3.0/onecall
  lat: 48.2149546
  lon: 16.302153494876826
  units: metric
  lang: de
  appid: abdb6964a969eeceed4f072180f1d3a7  # your api key
  interval: 300  # Call every 5 Minutes (300 seconds), so we have 288 calls per day

kivy:
  kv_directory: templates
  locale: de_DE.utf8
  mqtt_host: 192.168.0.200
  temperature_unit: °C
  pressure_unit: hPa
  humidity_unit: '%'
  battery_unit: mV
  wind_unit: m/s
  clouds_unit: '%'
