#:import SensorBme280Widget sensor_bme280_widget
#:import CurrentWidget current_widget
#:import ForecastHourlyWidget forecast_hourly_widget
#:import ForecastDailyWidget forecast_daily_widget
#:import utils kivy.utils

<SensorBme280Widget>:
    canvas.before:
        Color:
            rgba: utils.get_color_from_hex("#FFFFFF")
        RoundedRectangle:
            pos: self.x, self.y
            size: self.width, self.height
            radius: [10,]
    orientation: 'vertical'
    opacity: root.opacity

    BoxLayout: # Name
        size_hint: 1, 0.15
        orientation: 'horizontal'
        valign: 'top'

        Label:
            id: name
            size_hint: 1, 1
            width: self.texture_size[0]
            color: utils.get_color_from_hex("#2E2E2E")
            text: root.name
            text_size: self.size
            font_size: 18
            halign: 'center'

    BoxLayout: # Für Temperatur und Einheit
        size_hint: 1, 0.30
        orientation: 'horizontal'
        valign: 'top'
        padding: 5,0,5,0

        Label:
            id: temperature
            size_hint: None, 1
            width: self.texture_size[0]
            color: utils.get_color_from_hex("#F56101")
            text: root.temperature
            font_size: 46
            bold: True

        Label:
            id: temperature_unit
            color: utils.get_color_from_hex("#F56101")
            text: root.temperature_unit
            text_size: self.size
            font_size: 28
            halign: 'left'
            valign: 'top'

    BoxLayout: # 2. Zeile
        size_hint: 1, 0.19
        orientation: 'horizontal'
        padding: 10,0,0,0

        Image:
            size_hint: 0.10, 1
            source: 'icons/humidity.png'
            halign: 'left'
            valign: 'middle'
        Label:
            id: humidity
            size_hint: 0.50, 1
            padding: [5,0]
            color: utils.get_color_from_hex("#2E2E2E")
            halign: 'left'
            valign: 'middle'
            text: root.humidity
            text_size: self.size
            font_size: 20

    BoxLayout: # 3. Zeile
        size_hint: 1, 0.19
        orientation: 'horizontal'
        padding: 10,0,0,0

        Image:
            size_hint: 0.10, 1
            source: 'icons/pressure.png'
            halign: 'left'
            valign: 'middle'
        Label:
            id: pressure
            size_hint: 0.50, 1
            padding: [5,0]
            color: utils.get_color_from_hex("#2E2E2E")
            halign: 'left'
            valign: 'middle'
            text: root.pressure
            text_size: self.size
            font_size: 20

    BoxLayout: # 4. Zeile
        size_hint: 1, 0.17
        orientation: 'horizontal'
        padding: 5,0,5,0


        Label:
            id: battery
            size_hint: 0.25, 1
            padding: [0,0]
            color: utils.get_color_from_hex("#2E2E2E")
            halign: 'center'
            valign: 'middle'
            text: root.battery
            text_size: self.size
            font_size: 14
        Label:
            id: wifi
            size_hint: 0.45, 1
            padding: [0,0]
            color: utils.get_color_from_hex("#2E2E2E")
            halign: 'center'
            valign: 'middle'
            text: root.wifi
            text_size: self.size
            font_size: 14
        Label:
            id: last_update
            size_hint: 0.30, 1
            padding: [0,0]
            color: utils.get_color_from_hex("#2E2E2E")
            halign: 'center'
            valign: 'middle'
            text: root.last_update
            text_size: self.size
            font_size: 14




<CurrentWidget>:
    canvas.before:
        Color:
            rgba: utils.get_color_from_hex("#FFFFFF")
        RoundedRectangle:
            pos: self.x, self.y
            size: self.width, self.height
            radius: [10,]

    orientation: 'vertical'
    Label:
        id: time
        size_hint: 1, 0.15
        color: utils.get_color_from_hex("#2E2E2E")
        text: root.time
        text_size: self.size
        font_size: 24
        halign: 'center'
        valign: 'middle'
    BoxLayout:
        size_hint: 1, 0.85
        orientation: 'horizontal'
        AnchorLayout:
            size_hint: 0.35, 1
            anchor_x: 'center'
            anchor_y: 'center'
            padding: 10
            Image:
                id:weather
                source: root.icon
                size_hint: 1, 1
        BoxLayout: # rechte Seite neben Icon
            size_hint: 0.65, 1
            padding: [0,8,4,4]
            spacing: 5
            orientation: 'vertical'
            BoxLayout: # 1. Zeile auf der rechten Seite
                size_hint: 1, 0.4
                orientation: 'horizontal'

                BoxLayout: # Für Temperatur und Einheit
                    size_hint: 0.6, 1
                    orientation: 'horizontal'
                    Label:
                        id: temperature
                        size_hint: None, 1
                        width: self.texture_size[0]
                        color: utils.get_color_from_hex("#F56101")
                        text: root.temperature
                        font_size: 48
                        bold: True
                        halign: 'left'
                        valign: 'middle'
                    Label:
                        id: temperature_unit
                        padding: [2, 0]
                        color: utils.get_color_from_hex("#F56101")
                        text: root.temperature_unit
                        text_size: self.size
                        font_size: 28
                        halign: 'left'
                        valign: 'top'

                BoxLayout: # Zeilen mit max und min Werten
                    size_hint: 0.4, 1
                    orientation: 'vertical'
                    BoxLayout: # Für max Temperatur und Einheit
                        orientation: 'horizontal'
                        size_hint: 1, 1
                        Label:
                            id: max_temperature
                            color: utils.get_color_from_hex("#F40000")
                            text: root.max_temperature
                            padding: [5, 0]
                            size_hint: None, 1
                            width: self.texture_size[0]
                            font_size: 18
                            halign: 'left'
                            valign: 'middle'
                        Label:
                            id: max_temperature_unit
                            color: utils.get_color_from_hex("#F40000")
                            text: root.temperature_unit
                            text_size: self.size
                            font_size: 16
                            halign: 'left'
                            valign: 'top'
                    BoxLayout: # Für min Temperatur und Einheit
                        orientation: 'horizontal'
                        size_hint: 1, 1
                        Label:
                            id: min_temperature
                            color: utils.get_color_from_hex("#0000F4")
                            text: root.min_temperature
                            padding: [5, 0]
                            size_hint: None, 1
                            width: self.texture_size[0]
                            font_size: 18
                            halign: 'left'
                            valign: 'middle'
                        Label:
                            id: min_temperature_unit
                            color: utils.get_color_from_hex("#0000F4")
                            text: root.temperature_unit
                            text_size: self.size
                            font_size: 16
                            halign: 'left'
                            valign: 'top'

            BoxLayout: # 2. Zeile auf der rechten Seite
                size_hint: 1, 0.2
                orientation: 'horizontal'

                Image:
                    size_hint: 0.10, 1
                    source: 'icons/pressure.png'
                    halign: 'left'
                    valign: 'middle'
                Label:
                    id: pressure
                    size_hint: 0.50, 1
                    padding: [5,0]
                    color: utils.get_color_from_hex("#2E2E2E")
                    halign: 'left'
                    valign: 'middle'
                    text: root.pressure
                    text_size: self.size
                    font_size: 20

                Image:
                    size_hint: 0.1, 1
                    source: 'icons/humidity.png'
                    halign: 'left'
                    valign: 'middle'
                Label:
                    id: humidity
                    size_hint: 0.3, 1
                    padding: [5,0]
                    color: utils.get_color_from_hex("#2E2E2E")
                    halign: 'left'
                    valign: 'middle'
                    text: root.humidity
                    text_size: self.size
                    font_size: 20

            BoxLayout: # 3. Zeile auf der rechten Seite
                size_hint: 1, 0.2
                orientation: 'horizontal'

                Image:
                    canvas.before:
                        PushMatrix
                        Rotate:
                            angle: root.wind_deg
                            origin: self.center
                    canvas.after:
                        PopMatrix
                    source: 'icons/wind.png'
                    halign: 'left'
                    valign: 'middle'
                    size_hint: 0.1, 1
                Label:
                    id: wind
                    size_hint: 0.5, 1
                    padding: [5,0]
                    color: utils.get_color_from_hex("#2E2E2E")
                    halign: 'left'
                    valign: 'middle'
                    text: root.wind
                    text_size: self.size
                    font_size: 20

                Image:
                    source: 'icons/cloud.png'
                    halign: 'left'
                    valign: 'middle'
                    size_hint: 0.1, 1
                Label:
                    id: clouds
                    size_hint: 0.3, 1
                    padding: [5,0]
                    color: utils.get_color_from_hex("#2E2E2E")
                    halign: 'left'
                    valign: 'middle'
                    text: root.clouds
                    text_size: self.size
                    font_size: 20

            BoxLayout: # 4. Zeile auf der rechten Seite
                size_hint: 1, 0.2
                orientation: 'horizontal'

                Image:
                    source: 'icons/sunrise.png'
                    halign: 'left'
                    valign: 'middle'
                    size_hint: 0.1, 1
                Label:
                    id: sunrise
                    size_hint: 0.5, 1
                    padding: [5,0]
                    color: utils.get_color_from_hex("#2E2E2E")
                    halign: 'left'
                    valign: 'middle'
                    text: root.sunrise
                    text_size: self.size
                    font_size: 20

                Image:
                    source: 'icons/sunset.png'
                    halign: 'left'
                    valign: 'middle'
                    size_hint: 0.1, 1
                Label:
                    id: sunset
                    size_hint: 0.3, 1
                    padding: [5,0]
                    color: utils.get_color_from_hex("#2E2E2E")
                    halign: 'left'
                    valign: 'middle'
                    text: root.sunset
                    text_size: self.size
                    font_size: 20

<ForecastHourlyWidget>:
    canvas.before:
        Color:
            rgba: utils.get_color_from_hex("#FFFFFF")
        RoundedRectangle:
            pos: self.x, self.y
            size: self.width, self.height
            radius: [10,]

<ForecastDailyWidget>:
    canvas.before:
        Color:
            rgba: utils.get_color_from_hex("#FFFFFF")
        RoundedRectangle:
            pos: self.x, self.y
            size: self.width, self.height
            radius: [10,]

<WeatherStation>:
    BoxLayout:
        canvas.before:
            Color:
                rgb: utils.get_color_from_hex("#96C6F5")
            Rectangle:
                pos: self.x, self.y
                size: self.width, self.height

        orientation: 'vertical'
        size: 800, 480
        spacing: 5
        padding: 5

        BoxLayout:
            spacing: 5
            size_hint: 1, 0.35
            orientation: 'horizontal'
            CurrentWidget:
                id: current_widget
                size_hint: 0.46, 1
            SensorBme280Widget:
                name: "Balkon"
                topic: '/weatherstation/sensor/00'
                size_hint: 0.18, 1
            SensorBme280Widget:
                name: "Wohnzimmer"
                topic: '/weatherstation/sensor/01'
                size_hint: 0.18, 1
            SensorBme280Widget:
                name: "Schlafzimmer"
                topic: '/weatherstation/sensor/02'
                size_hint: 0.18, 1

        BoxLayout:
            spacing: 5
            padding: 0
            size_hint: 1, 0.65
            orientation: 'horizontal'
            ForecastHourlyWidget:
                id: forecast_hourly_widget
                size_hint: 0.5, 1
            ForecastDailyWidget:
                id: forecast_daily_widget
                size_hint: 0.5, 1
